### ISSUE TITLE
Data is been fetched with API but pictures of data cannot be seen

### ISSUE THREAD

**Issue by Dorcastunmise** [Dorcastunmise/books-app#1]
![Screenshot (162)](https://user-images.githubusercontent.com/105108549/191206252-523791fb-c519-4bf6-9a98-3c1e4ca08c39.png)

**Comment by dangvu0502** [comment]
I have just take a look.
I try to search "react" keyword then press enter.  
It seem like everything works well ?

![image](https://user-images.githubusercontent.com/57172125/191214331-6bbe50c7-7f92-4a34-8507-18e4dcf8fbaf.png)

**Comment by Dorcastunmise** [comment]
Wow...okay I'm speechless

**Comment by Dorcastunmise** [comment]
It's still not showing over here . :(

**Comment by dangvu0502** [comment]
Can you give me more details about this? 
How can i reproduce your issue? Can you record a video about this? or somethings like that ....

**Comment by Dorcastunmise** [comment]
https://user-images.githubusercontent.com/105108549/191222769-8767e1b4-f155-4677-8ef7-0a5014f2ad4b.mp4

**Comment by Dorcastunmise** [comment]
I've sorted the issue.
